import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'

const retroFloral = localFont({
  src: '../../public/fonts/retro-floral.woff2',
  display: 'swap',
  variable: '--font-retro'
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body className={`${retroFloral.variable} antialiased`} >
        {/* <h1 className="font-retro text-[48px] ">
          From <br /> nothing <br /> courses
        </h1> */}
        {children}
      </body>
    </html>
  );
}
